Provide enclosure character for str_getcsv
With PHP 8.4 `str_getcsv` will require a single character to be provided as enclosure. Passing an empty string results in 
```
ValueError: str_getcsv(): Argument #3 ($enclosure) must be a single character
```